# Generated by Django 6.1 on 2026-08-10 18:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Dataset",
            fields=[
                ("id", models.TextField(primary_key=True, serialize=False)),
                ("org_slug", models.TextField()),
                ("org_display_name", models.TextField(blank=True, null=True)),
                ("title", models.TextField(blank=True, null=True)),
                ("name", models.TextField(blank=True, null=True)),
                ("notes", models.TextField(blank=True, null=True)),
                ("metadata_created", models.TextField(blank=True, null=True)),
                ("metadata_modified", models.TextField(blank=True, null=True)),
                ("resource_count", models.IntegerField(blank=True, null=True)),
                ("theme_primary", models.TextField(blank=True, null=True)),
                ("temporal_coverage_from", models.TextField(blank=True, null=True)),
                ("temporal_coverage_to", models.TextField(blank=True, null=True)),
                ("temporal_granularity", models.TextField(blank=True, null=True)),
                ("temporal_periods", models.TextField(blank=True, null=True)),
                ("harvested", models.IntegerField(db_default=0)),
                ("harvest_source_title", models.TextField(blank=True, null=True)),
                ("views", models.IntegerField(db_default=0)),
                ("tags", models.TextField(blank=True, null=True)),
            ],
            options={
                "db_table": "datasets",
            },
        ),
        migrations.CreateModel(
            name="DatasetEmbedding",
            fields=[
                ("rowid", models.IntegerField(primary_key=True, serialize=False)),
            ],
            options={
                "db_table": "dataset_embeddings",
            },
        ),
        migrations.CreateModel(
            name="MetadataKey",
            fields=[
                ("key", models.TextField(primary_key=True, serialize=False)),
                ("section", models.TextField()),
                ("count", models.IntegerField()),
                ("non_empty", models.IntegerField()),
                ("distinct_values", models.IntegerField()),
            ],
            options={
                "db_table": "metadata_keys",
            },
        ),
        migrations.CreateModel(
            name="Organisation",
            fields=[
                ("slug", models.TextField(primary_key=True, serialize=False)),
                ("name", models.TextField(blank=True, null=True)),
                ("display_name", models.TextField(blank=True, null=True)),
                ("package_count", models.IntegerField(blank=True, null=True)),
                ("type", models.TextField(blank=True, null=True)),
                ("state", models.TextField(blank=True, null=True)),
                ("approval_status", models.TextField(blank=True, null=True)),
                ("created", models.TextField(blank=True, null=True)),
                ("title", models.TextField(blank=True, null=True)),
                ("json", models.TextField(blank=True, null=True)),
            ],
            options={
                "db_table": "organisations",
            },
        ),
        migrations.CreateModel(
            name="DatasetJson",
            fields=[
                (
                    "dataset",
                    models.OneToOneField(
                        db_column="id",
                        db_index=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to="explorer.dataset",
                    ),
                ),
                ("json", models.TextField()),
            ],
            options={
                "db_table": "dataset_json",
            },
        ),
        migrations.CreateModel(
            name="EmbeddingMap",
            fields=[
                ("rowid", models.IntegerField(primary_key=True, serialize=False)),
                ("vector_text", models.TextField()),
                (
                    "dataset",
                    models.ForeignKey(
                        db_column="dataset_id",
                        db_index=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="explorer.dataset",
                    ),
                ),
            ],
            options={
                "db_table": "embedding_map",
            },
        ),
        migrations.CreateModel(
            name="Link",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("resource_id", models.TextField(blank=True, null=True)),
                ("org_slug", models.TextField()),
                ("org_display_name", models.TextField(blank=True, null=True)),
                ("dataset_title", models.TextField(blank=True, null=True)),
                ("name", models.TextField(blank=True, null=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("url", models.TextField(blank=True, null=True)),
                ("host", models.TextField(blank=True, null=True)),
                ("format", models.TextField(blank=True, null=True)),
                ("format_norm", models.TextField(blank=True, null=True)),
                ("year_created", models.TextField(blank=True, null=True)),
                ("created", models.TextField(blank=True, null=True)),
                ("position", models.IntegerField(blank=True, null=True)),
                (
                    "dataset",
                    models.ForeignKey(
                        db_column="dataset_id",
                        db_index=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="explorer.dataset",
                    ),
                ),
            ],
            options={
                "db_table": "links",
            },
        ),
        migrations.CreateModel(
            name="MetadataValue",
            fields=[
                ("value", models.TextField()),
                ("count", models.IntegerField()),
                (
                    "pk",
                    models.CompositePrimaryKey(
                        "metadata_key",
                        "value",
                        blank=True,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "metadata_key",
                    models.ForeignKey(
                        db_column="key",
                        db_index=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="explorer.metadatakey",
                    ),
                ),
            ],
            options={
                "db_table": "metadata_values",
            },
        ),
        migrations.CreateModel(
            name="Series",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("root_title", models.TextField()),
                ("type", models.TextField()),
                ("dataset_count", models.IntegerField(db_default=0)),
                ("org_count", models.IntegerField(db_default=0)),
            ],
            options={
                "db_table": "series",
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("type__in", ("template", "timeseries"))),
                        name="series_type_check",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="SeriesDataset",
            fields=[
                ("dataset_id", models.TextField()),
                ("dataset_title", models.TextField()),
                ("date_suffix", models.TextField(blank=True, null=True)),
                ("org_slug", models.TextField()),
                ("org_display_name", models.TextField()),
                (
                    "pk",
                    models.CompositePrimaryKey(
                        "series",
                        "dataset_id",
                        blank=True,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "series",
                    models.ForeignKey(
                        db_column="series_id",
                        db_index=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="explorer.series",
                    ),
                ),
            ],
            options={
                "db_table": "series_datasets",
            },
        ),
    ]
