# Generated by Django 6.1 on 2026-08-11 23:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("explorer", "0003_indexes"),
    ]

    operations = [
        migrations.CreateModel(
            name="Review",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("ok", models.BooleanField(db_default=True)),
                ("overall", models.IntegerField(blank=True, null=True)),
                ("findability", models.IntegerField(blank=True, null=True)),
                ("metadata", models.IntegerField(blank=True, null=True)),
                ("resources", models.IntegerField(blank=True, null=True)),
                ("theme", models.TextField(blank=True, null=True)),
                ("tags", models.TextField(blank=True, null=True)),
                ("title", models.TextField(blank=True, null=True)),
                ("desc", models.TextField(blank=True, null=True)),
                ("theme_confidence", models.TextField(blank=True, null=True)),
                ("created_at", models.TextField(blank=True, null=True)),
                ("json", models.TextField()),
                (
                    "dataset",
                    models.ForeignKey(
                        db_column="dataset_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="explorer.dataset",
                    ),
                ),
            ],
            options={
                "db_table": "reviews",
            },
        ),
    ]
